import math



# <--- game parameters --->

#generics
SCREENW, SCREENH = 800,600
FPS = 120
PI = math.pi
POINTS_TO_WIN = 25

#ball
BALL_SIZE = 24
BALL_SPEED = 500 / FPS
NEWBALL_DELAY = 1 * FPS

#pad
PAD_W, PAD_H = 10, 100
PAD_MAX_SPEED = 500 / FPS
PAD_TIME_2_MAX_SPEED = .2 * FPS #s
PAD_ACC = PAD_MAX_SPEED / PAD_TIME_2_MAX_SPEED
PAD_FRICTION = .5
PAD_MAX_ANGLESPAN = PI/4

PAD_LOSING_ANIMATION_TIME = 1 * FPS
PAD_LOSING_FLASHES = 3 * 2
PAD_LOSING_FLASH_TIME = int(PAD_LOSING_ANIMATION_TIME / PAD_LOSING_FLASHES)

#wall
WALL_W = 5

#pwups
PWUP_MIN_SPAWN_TIME = 5 * FPS
PWUP_MAX_SPAWN_TIME = 10 * FPS

PWUP_H, PWUP_W = BALL_SIZE, BALL_SIZE
PWUP_MIN_X, PWUP_MAX_X = 100+PWUP_W/2, SCREENW-100-PWUP_W/2
PWUP_MIN_Y, PWUP_MAX_Y = PWUP_H/2, SCREENH-PWUP_H/2

PWUP_MIN_MULT = 2
PWUP_MAX_MULT = 5

PWUP_MIN_FREEZE_TIME = 1 * FPS
PWUP_MAX_FREEZE_TIME = 3 * FPS

PWUP_MINIMIZE_H = PAD_H * 1/2
PWUP_MAXIMIZE_H = PAD_H * 2
PWUP_MAXMIN_TIME = 10 * FPS

PWUP_WALL_TIME = 10 * FPS

PWUP_MIN_BALL_VALUE = 2
PWUP_MAX_BALL_VALUE = 5

PWUP_SPEED = 1.8 * BALL_SPEED

#colors
WHITE = (255,255,255)
BLACK = (0,0,0)
LIGHTGREY = (100,100,100)
RED = (255,0,0)
YELLOW = (255,255,0)
GREEN = (0,255,0)
LIGHTBLUE = (128,128,255)
GRAY = (128,128,128)
ORANGE = (255,128,0)
VIOLET = (128,0,128)

PWUP_COLORS = {'mult':YELLOW,
               'freeze':LIGHTBLUE,
               'maxpad':GREEN,
               'minpad':RED,
               'wall':GRAY,
               'value':ORANGE,
               'speed':VIOLET,
               'ghost':WHITE}